import { DataSource } from 'typeorm';
import * as bcrypt from 'bcrypt';
import { User } from '../users/entities/user.entity';
import { Report } from '../reports/entities/report.entity';
import { Listing } from '../marketplace/entities/listing.entity';
import { SavedCar } from '../users/entities/saved-car.entity';
import { UserRole } from '../auth/dto/register.dto';

async function seed() {
  const dataSource = new DataSource({
    type: 'postgres',
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '5432', 10),
    username: process.env.DB_USERNAME || 'postgres',
    password: process.env.DB_PASSWORD || 'postgres',
    database: process.env.DB_DATABASE || 'car_health_platform',
    entities: [__dirname + '/../**/*.entity{.ts,.js}'],
    synchronize: false,
    logging: false,
  });

  try {
    await dataSource.initialize();
    console.log('✅ Database connected');

    const userRepository = dataSource.getRepository(User);
    const reportRepository = dataSource.getRepository(Report);
    const listingRepository = dataSource.getRepository(Listing);
    const savedCarRepository = dataSource.getRepository(SavedCar);

    // Clear existing data (optional - comment out if you want to keep existing data)
    // Must delete in order due to foreign key constraints
    console.log('🗑️  Clearing existing data...');
    
    // First, delete saved_cars (references listings)
    await savedCarRepository.createQueryBuilder().delete().execute();
    console.log('   ✓ Cleared saved_cars');
    
    // Then delete listings (references reports and users)
    await listingRepository.createQueryBuilder().delete().execute();
    console.log('   ✓ Cleared listings');
    
    // Then delete reports (references users)
    await reportRepository.createQueryBuilder().delete().execute();
    console.log('   ✓ Cleared reports');
    
    // Delete specific test users if they exist (by email or phone)
    const testEmails = [
      'seller1@test.com', 'seller2@test.com', 'seller3@test.com',
      'seller4@test.com', 'seller5@test.com', 'seller6@test.com',
      'seller7@test.com', 'seller8@test.com', 'seller9@test.com',
      'seller10@test.com', 'seller11@test.com', 'seller12@test.com',
      'seller13@test.com', 'seller14@test.com', 'seller15@test.com',
    ];
    const testPhones = [
      '+1234567890', '+1234567891', '+1234567892',
      '+1234567893', '+1234567894', '+1234567895',
      '+1234567896', '+1234567897', '+1234567898',
      '+1234567899', '+1234567900', '+1234567901',
      '+1234567902', '+1234567903', '+1234567904',
    ];
    
    const existingUsersByEmail = await userRepository.find({
      where: testEmails.map(email => ({ email })),
      withDeleted: true, // Include soft-deleted users
    });
    
    const existingUsersByPhone = await userRepository.find({
      where: testPhones.map(phone => ({ phone })),
      withDeleted: true,
    });
    
    const allExistingUsers = [...existingUsersByEmail, ...existingUsersByPhone];
    const uniqueUsers = Array.from(new Map(allExistingUsers.map(u => [u.id, u])).values());
    
    if (uniqueUsers.length > 0) {
      // Hard delete (remove completely, not soft delete)
      await userRepository.remove(uniqueUsers);
      console.log(`   ✓ Removed ${uniqueUsers.length} existing test users`);
    }

    // Create test users
    console.log('👤 Creating test users...');
    const hashedPassword = await bcrypt.hash('password123', 10);

    const users = [
      {
        email: 'seller1@test.com',
        password: hashedPassword,
        phone: '+1234567890',
        role: UserRole.SELLER,
        firstName: 'John',
        lastName: 'Doe',
        city: 'Los Angeles',
        state: 'California',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller2@test.com',
        password: hashedPassword,
        phone: '+1234567891',
        role: UserRole.SELLER,
        firstName: 'Jane',
        lastName: 'Smith',
        city: 'New York',
        state: 'New York',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller3@test.com',
        password: hashedPassword,
        phone: '+1234567892',
        role: UserRole.SELLER,
        firstName: 'Mike',
        lastName: 'Johnson',
        city: 'Miami',
        state: 'Florida',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller4@test.com',
        password: hashedPassword,
        phone: '+1234567893',
        role: UserRole.SELLER,
        firstName: 'Sarah',
        lastName: 'Williams',
        city: 'Chicago',
        state: 'Illinois',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller5@test.com',
        password: hashedPassword,
        phone: '+1234567894',
        role: UserRole.SELLER,
        firstName: 'David',
        lastName: 'Brown',
        city: 'Houston',
        state: 'Texas',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller6@test.com',
        password: hashedPassword,
        phone: '+1234567895',
        role: UserRole.SELLER,
        firstName: 'Emily',
        lastName: 'Davis',
        city: 'Phoenix',
        state: 'Arizona',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller7@test.com',
        password: hashedPassword,
        phone: '+1234567896',
        role: UserRole.SELLER,
        firstName: 'Robert',
        lastName: 'Miller',
        city: 'Seattle',
        state: 'Washington',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller8@test.com',
        password: hashedPassword,
        phone: '+1234567897',
        role: UserRole.SELLER,
        firstName: 'Lisa',
        lastName: 'Wilson',
        city: 'Boston',
        state: 'Massachusetts',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller9@test.com',
        password: hashedPassword,
        phone: '+1234567898',
        role: UserRole.SELLER,
        firstName: 'James',
        lastName: 'Moore',
        city: 'Denver',
        state: 'Colorado',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller10@test.com',
        password: hashedPassword,
        phone: '+1234567899',
        role: UserRole.SELLER,
        firstName: 'Patricia',
        lastName: 'Taylor',
        city: 'Atlanta',
        state: 'Georgia',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller11@test.com',
        password: hashedPassword,
        phone: '+1234567900',
        role: UserRole.SELLER,
        firstName: 'Michael',
        lastName: 'Anderson',
        city: 'San Francisco',
        state: 'California',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller12@test.com',
        password: hashedPassword,
        phone: '+1234567901',
        role: UserRole.SELLER,
        firstName: 'Jennifer',
        lastName: 'Thomas',
        city: 'Portland',
        state: 'Oregon',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller13@test.com',
        password: hashedPassword,
        phone: '+1234567902',
        role: UserRole.SELLER,
        firstName: 'William',
        lastName: 'Jackson',
        city: 'Dallas',
        state: 'Texas',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller14@test.com',
        password: hashedPassword,
        phone: '+1234567903',
        role: UserRole.SELLER,
        firstName: 'Linda',
        lastName: 'White',
        city: 'Las Vegas',
        state: 'Nevada',
        country: 'USA',
        isActive: true,
      },
      {
        email: 'seller15@test.com',
        password: hashedPassword,
        phone: '+1234567904',
        role: UserRole.SELLER,
        firstName: 'Richard',
        lastName: 'Harris',
        city: 'Nashville',
        state: 'Tennessee',
        country: 'USA',
        isActive: true,
      },
    ];

    const savedUsers = await userRepository.save(users);
    console.log(`✅ Created ${savedUsers.length} users`);

    // Create test reports with images
    console.log('📊 Creating test reports...');
    
    // Helper function to generate car images (using Unsplash car photos)
    const getCarImages = (index: number) => {
      const imageSets = [
        // Set 1 - Sedan/Coupe
        [
          'https://images.unsplash.com/photo-1492144534655-ae79c2c034d7?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1549317661-bd32c8b0c2a3?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1606664515524-9f283c033ba2?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&h=600&fit=crop&auto=format',
        ],
        // Set 2 - SUV/Truck
        [
          'https://images.unsplash.com/photo-1606664515524-9f283c033ba2?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1549317661-bd32c8b0c2a3?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1492144534655-ae79c2c034d7?w=800&h=600&fit=crop&auto=format',
        ],
        // Set 3 - Luxury
        [
          'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1549317661-bd32c8b0c2a3?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop&auto=format',
        ],
        // Set 4 - Electric
        [
          'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1606664515524-9f283c033ba2?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1492144534655-ae79c2c034d7?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1549317661-bd32c8b0c2a3?w=800&h=600&fit=crop&auto=format',
          'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&h=600&fit=crop&auto=format',
        ],
      ];
      return imageSets[index % imageSets.length];
    };

    const reports = [
      {
        userId: savedUsers[0].id,
        make: 'Toyota',
        model: 'Camry',
        year: 2020,
        carDetails: {
          kilometersDriven: 45000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Silver',
          ownershipCount: 1,
          vin: '4T1B11HK5JU123456',
          registrationNumber: 'CA-ABC123',
          city: 'Los Angeles',
          state: 'California',
          country: 'USA',
          engine: '2.5L 4-Cylinder',
          drivetrain: 'FWD',
          condition: 'Excellent',
          features: ['Bluetooth', 'Backup Camera', 'Cruise Control', 'Keyless Entry'],
        },
        media: { images: getCarImages(0), videos: [] },
        aiAnalysis: {
          overallScore: 92,
          status: 'completed',
          summary: 'Excellent condition vehicle with low mileage and well-maintained.',
          highlights: ['Low mileage', 'Single owner', 'Regular maintenance records'],
          issues: [],
          recommendations: ['Regular oil changes', 'Tire rotation recommended'],
        },
        trustScore: 92.5,
        verdict: 'Excellent',
        status: 'completed',
      },
      {
        userId: savedUsers[1].id,
        make: 'Honda',
        model: 'Civic',
        year: 2019,
        carDetails: {
          kilometersDriven: 52000,
          fuelType: 'Gasoline',
          transmission: 'CVT',
          color: 'Blue',
          ownershipCount: 1,
          vin: '19XFC2F59KE123456',
          registrationNumber: 'NY-XYZ789',
          city: 'New York',
          state: 'New York',
          country: 'USA',
          engine: '1.5L Turbo 4-Cylinder',
          drivetrain: 'FWD',
          condition: 'Very Good',
          features: ['Apple CarPlay', 'Android Auto', 'Lane Assist', 'Adaptive Cruise Control'],
        },
        media: { images: getCarImages(0), videos: [] },
        aiAnalysis: {
          overallScore: 88,
          status: 'completed',
          summary: 'Well-maintained vehicle with modern features and good reliability.',
          highlights: ['Modern tech features', 'Good fuel economy'],
          issues: ['Minor wear on driver seat'],
          recommendations: ['Check brake pads', 'Replace air filter'],
        },
        trustScore: 88.0,
        verdict: 'Very Good',
        status: 'completed',
      },
      {
        userId: savedUsers[0].id,
        make: 'Ford',
        model: 'F-150',
        year: 2021,
        carDetails: {
          kilometersDriven: 35000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Black',
          ownershipCount: 1,
          vin: '1FTFW1E58MFA12345',
          registrationNumber: 'CA-DEF456',
          city: 'Los Angeles',
          state: 'California',
          country: 'USA',
          engine: '3.5L V6 EcoBoost',
          drivetrain: '4WD',
          condition: 'Excellent',
          features: ['4WD', 'Towing Package', 'Backup Camera', 'Bluetooth', 'Navigation'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 95,
          status: 'completed',
          summary: 'Like-new condition truck with low mileage and premium features.',
          highlights: ['Low mileage', 'Premium trim', 'Well-maintained'],
          issues: [],
          recommendations: ['Continue regular maintenance'],
        },
        trustScore: 95.0,
        verdict: 'Excellent',
        status: 'completed',
      },
      {
        userId: savedUsers[2].id,
        make: 'Tesla',
        model: 'Model 3',
        year: 2022,
        carDetails: {
          kilometersDriven: 18000,
          fuelType: 'Electric',
          transmission: 'Single-Speed',
          color: 'White',
          ownershipCount: 1,
          vin: '5YJ3E1EA8NF123456',
          registrationNumber: 'FL-GHI789',
          city: 'Miami',
          state: 'Florida',
          country: 'USA',
          engine: 'Electric Motor',
          drivetrain: 'RWD',
          condition: 'Like New',
          features: ['Autopilot', 'Supercharging', 'Premium Interior', 'Full Self-Driving Capable'],
        },
        media: { images: getCarImages(3), videos: [] },
        aiAnalysis: {
          overallScore: 98,
          status: 'completed',
          summary: 'Nearly new electric vehicle with cutting-edge technology and minimal wear.',
          highlights: ['Very low mileage', 'Latest tech', 'Excellent battery health'],
          issues: [],
          recommendations: ['Battery health check recommended'],
        },
        trustScore: 98.0,
        verdict: 'Like New',
        status: 'completed',
      },
      {
        userId: savedUsers[1].id,
        make: 'BMW',
        model: '3 Series',
        year: 2020,
        carDetails: {
          kilometersDriven: 38000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Metallic Gray',
          ownershipCount: 1,
          vin: 'WBA5A5C58ED123456',
          registrationNumber: 'NY-JKL012',
          city: 'New York',
          state: 'New York',
          country: 'USA',
          engine: '2.0L Turbo 4-Cylinder',
          drivetrain: 'RWD',
          condition: 'Very Good',
          features: ['Leather Seats', 'Sunroof', 'Navigation', 'Premium Sound', 'Parking Sensors'],
        },
        media: { images: getCarImages(2), videos: [] },
        aiAnalysis: {
          overallScore: 90,
          status: 'completed',
          summary: 'Luxury sedan in excellent condition with premium features.',
          highlights: ['Premium features', 'Well-maintained', 'Good condition'],
          issues: [],
          recommendations: ['Premium fuel recommended', 'Regular service at BMW dealer'],
        },
        trustScore: 90.0,
        verdict: 'Very Good',
        status: 'completed',
      },
      {
        userId: savedUsers[2].id,
        make: 'Mercedes-Benz',
        model: 'C-Class',
        year: 2021,
        carDetails: {
          kilometersDriven: 28000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Black',
          ownershipCount: 1,
          vin: 'WDDWF4KB1MR123456',
          registrationNumber: 'FL-MNO345',
          city: 'Miami',
          state: 'Florida',
          country: 'USA',
          engine: '2.0L Turbo 4-Cylinder',
          drivetrain: 'RWD',
          condition: 'Excellent',
          features: ['MBUX Infotainment', 'Panoramic Sunroof', 'Burmester Sound', 'AMG Line'],
        },
        media: { images: getCarImages(2), videos: [] },
        aiAnalysis: {
          overallScore: 93,
          status: 'completed',
          summary: 'Premium luxury vehicle with advanced technology and excellent condition.',
          highlights: ['Low mileage', 'Premium trim', 'Excellent condition'],
          issues: [],
          recommendations: ['Maintain service records', 'Premium fuel only'],
        },
        trustScore: 93.0,
        verdict: 'Excellent',
        status: 'completed',
      },
      {
        userId: savedUsers[3].id,
        make: 'Audi',
        model: 'A4',
        year: 2020,
        carDetails: {
          kilometersDriven: 42000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Navy Blue',
          ownershipCount: 1,
          vin: 'WAUAF48H20K123456',
          registrationNumber: 'IL-PQR678',
          city: 'Chicago',
          state: 'Illinois',
          country: 'USA',
          engine: '2.0L Turbo 4-Cylinder',
          drivetrain: 'AWD',
          condition: 'Very Good',
          features: ['Virtual Cockpit', 'Bang & Olufsen Sound', 'Quattro AWD', 'Leather Seats'],
        },
        media: { images: getCarImages(2), videos: [] },
        aiAnalysis: {
          overallScore: 89,
          status: 'completed',
          summary: 'Well-maintained luxury sedan with all-wheel drive and premium features.',
          highlights: ['AWD system', 'Premium audio', 'Modern tech'],
          issues: ['Minor scratches on front bumper'],
          recommendations: ['Regular Audi service', 'Premium fuel'],
        },
        trustScore: 89.0,
        verdict: 'Very Good',
        status: 'completed',
      },
      {
        userId: savedUsers[4].id,
        make: 'Nissan',
        model: 'Altima',
        year: 2019,
        carDetails: {
          kilometersDriven: 58000,
          fuelType: 'Gasoline',
          transmission: 'CVT',
          color: 'Red',
          ownershipCount: 2,
          vin: '1N4AL3AP8KC123456',
          registrationNumber: 'TX-STU901',
          city: 'Houston',
          state: 'Texas',
          country: 'USA',
          engine: '2.5L 4-Cylinder',
          drivetrain: 'FWD',
          condition: 'Good',
          features: ['Nissan Safety Shield', 'Apple CarPlay', 'Bluetooth', 'Backup Camera'],
        },
        media: { images: getCarImages(0), videos: [] },
        aiAnalysis: {
          overallScore: 82,
          status: 'completed',
          summary: 'Reliable sedan with good features, some wear expected for mileage.',
          highlights: ['Safety features', 'Good reliability'],
          issues: ['Some interior wear', 'Tires may need replacement soon'],
          recommendations: ['Replace tires', 'Check CVT fluid'],
        },
        trustScore: 82.0,
        verdict: 'Good',
        status: 'completed',
      },
      {
        userId: savedUsers[5].id,
        make: 'Hyundai',
        model: 'Tucson',
        year: 2021,
        carDetails: {
          kilometersDriven: 32000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'White',
          ownershipCount: 1,
          vin: '5NPE34AF5MH123456',
          registrationNumber: 'AZ-VWX234',
          city: 'Phoenix',
          state: 'Arizona',
          country: 'USA',
          engine: '2.5L 4-Cylinder',
          drivetrain: 'FWD',
          condition: 'Very Good',
          features: ['Apple CarPlay', 'Android Auto', 'Blind Spot Monitor', 'Lane Keep Assist'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 87,
          status: 'completed',
          summary: 'Modern SUV with good safety features and low mileage.',
          highlights: ['Low mileage', 'Safety features', 'Good warranty'],
          issues: [],
          recommendations: ['Regular maintenance'],
        },
        trustScore: 87.0,
        verdict: 'Very Good',
        status: 'completed',
      },
      {
        userId: savedUsers[6].id,
        make: 'Subaru',
        model: 'Outback',
        year: 2020,
        carDetails: {
          kilometersDriven: 48000,
          fuelType: 'Gasoline',
          transmission: 'CVT',
          color: 'Green',
          ownershipCount: 1,
          vin: '4S4BSANC9L3123456',
          registrationNumber: 'WA-YZA567',
          city: 'Seattle',
          state: 'Washington',
          country: 'USA',
          engine: '2.5L Boxer 4-Cylinder',
          drivetrain: 'AWD',
          condition: 'Very Good',
          features: ['Subaru EyeSight', 'AWD', 'Roof Rails', 'All-Weather Package'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 88,
          status: 'completed',
          summary: 'Reliable AWD vehicle perfect for all-weather conditions.',
          highlights: ['AWD system', 'Safety features', 'Good for outdoor activities'],
          issues: [],
          recommendations: ['Check CVT fluid', 'Regular maintenance'],
        },
        trustScore: 88.0,
        verdict: 'Very Good',
        status: 'completed',
      },
      {
        userId: savedUsers[7].id,
        make: 'Mazda',
        model: 'CX-5',
        year: 2021,
        carDetails: {
          kilometersDriven: 29000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Soul Red',
          ownershipCount: 1,
          vin: 'JM3KFBDM5M1123456',
          registrationNumber: 'MA-BCD890',
          city: 'Boston',
          state: 'Massachusetts',
          country: 'USA',
          engine: '2.5L Skyactiv-G',
          drivetrain: 'AWD',
          condition: 'Excellent',
          features: ['Mazda Connect', 'i-Activsense', 'Bose Audio', 'Power Liftgate'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 91,
          status: 'completed',
          summary: 'Excellent SUV with premium features and low mileage.',
          highlights: ['Low mileage', 'Premium features', 'Great handling'],
          issues: [],
          recommendations: ['Continue regular maintenance'],
        },
        trustScore: 91.0,
        verdict: 'Excellent',
        status: 'completed',
      },
      {
        userId: savedUsers[8].id,
        make: 'Chevrolet',
        model: 'Silverado',
        year: 2020,
        carDetails: {
          kilometersDriven: 55000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Gray',
          ownershipCount: 1,
          vin: '1GCVKREC0LZ123456',
          registrationNumber: 'CO-EFG123',
          city: 'Denver',
          state: 'Colorado',
          country: 'USA',
          engine: '5.3L V8',
          drivetrain: '4WD',
          condition: 'Good',
          features: ['4WD', 'Towing Package', 'Chevrolet Infotainment', 'Backup Camera'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 84,
          status: 'completed',
          summary: 'Powerful truck with good towing capacity, some wear expected.',
          highlights: ['Powerful engine', 'Good towing capacity'],
          issues: ['Some interior wear', 'Tires showing wear'],
          recommendations: ['Replace tires', 'Check brake pads'],
        },
        trustScore: 84.0,
        verdict: 'Good',
        status: 'completed',
      },
      {
        userId: savedUsers[9].id,
        make: 'Jeep',
        model: 'Wrangler',
        year: 2021,
        carDetails: {
          kilometersDriven: 25000,
          fuelType: 'Gasoline',
          transmission: 'Manual',
          color: 'Yellow',
          ownershipCount: 1,
          vin: '1C4HJXDN9MW123456',
          registrationNumber: 'GA-HIJ456',
          city: 'Atlanta',
          state: 'Georgia',
          country: 'USA',
          engine: '3.6L V6',
          drivetrain: '4WD',
          condition: 'Excellent',
          features: ['4WD', 'Removable Doors', 'Removable Top', 'Off-Road Package'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 92,
          status: 'completed',
          summary: 'Excellent off-road vehicle with low mileage and premium features.',
          highlights: ['Low mileage', 'Off-road capable', 'Unique features'],
          issues: [],
          recommendations: ['Regular maintenance', 'Check for off-road damage'],
        },
        trustScore: 92.0,
        verdict: 'Excellent',
        status: 'completed',
      },
      {
        userId: savedUsers[10].id,
        make: 'Volkswagen',
        model: 'Jetta',
        year: 2019,
        carDetails: {
          kilometersDriven: 60000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Black',
          ownershipCount: 2,
          vin: '3VW2B7AJ5KM123456',
          registrationNumber: 'CA-KLM789',
          city: 'San Francisco',
          state: 'California',
          country: 'USA',
          engine: '1.4L Turbo 4-Cylinder',
          drivetrain: 'FWD',
          condition: 'Good',
          features: ['Apple CarPlay', 'Android Auto', 'Bluetooth', 'Backup Camera'],
        },
        media: { images: getCarImages(0), videos: [] },
        aiAnalysis: {
          overallScore: 80,
          status: 'completed',
          summary: 'Reliable compact sedan with good fuel economy.',
          highlights: ['Good fuel economy', 'Reliable'],
          issues: ['Higher mileage', 'Some wear'],
          recommendations: ['Replace timing belt', 'Check suspension'],
        },
        trustScore: 80.0,
        verdict: 'Good',
        status: 'completed',
      },
      {
        userId: savedUsers[11].id,
        make: 'Kia',
        model: 'Telluride',
        year: 2022,
        carDetails: {
          kilometersDriven: 15000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Gravity Gray',
          ownershipCount: 1,
          vin: '5XYP3DHC5NG123456',
          registrationNumber: 'OR-NOP012',
          city: 'Portland',
          state: 'Oregon',
          country: 'USA',
          engine: '3.8L V6',
          drivetrain: 'AWD',
          condition: 'Like New',
          features: ['Apple CarPlay', 'Android Auto', 'Premium Sound', 'Third Row Seating'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 96,
          status: 'completed',
          summary: 'Nearly new large SUV with premium features and very low mileage.',
          highlights: ['Very low mileage', 'Premium features', 'Spacious'],
          issues: [],
          recommendations: ['Continue regular maintenance'],
        },
        trustScore: 96.0,
        verdict: 'Like New',
        status: 'completed',
      },
      {
        userId: savedUsers[12].id,
        make: 'Ram',
        model: '1500',
        year: 2020,
        carDetails: {
          kilometersDriven: 45000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Blue',
          ownershipCount: 1,
          vin: '1C6RR7FT0KS123456',
          registrationNumber: 'TX-QRS345',
          city: 'Dallas',
          state: 'Texas',
          country: 'USA',
          engine: '5.7L HEMI V8',
          drivetrain: '4WD',
          condition: 'Very Good',
          features: ['4WD', 'Uconnect Infotainment', 'Towing Package', 'Backup Camera'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 86,
          status: 'completed',
          summary: 'Powerful truck with good features and well-maintained.',
          highlights: ['Powerful engine', 'Good features'],
          issues: [],
          recommendations: ['Regular maintenance', 'Check brake pads'],
        },
        trustScore: 86.0,
        verdict: 'Very Good',
        status: 'completed',
      },
      {
        userId: savedUsers[13].id,
        make: 'Lexus',
        model: 'RX 350',
        year: 2021,
        carDetails: {
          kilometersDriven: 22000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Pearl White',
          ownershipCount: 1,
          vin: '2T2ZM1DA1MC123456',
          registrationNumber: 'NV-TUV678',
          city: 'Las Vegas',
          state: 'Nevada',
          country: 'USA',
          engine: '3.5L V6',
          drivetrain: 'AWD',
          condition: 'Excellent',
          features: ['Lexus Safety System+', 'Premium Audio', 'Panoramic Roof', 'Leather Seats'],
        },
        media: { images: getCarImages(2), videos: [] },
        aiAnalysis: {
          overallScore: 94,
          status: 'completed',
          summary: 'Luxury SUV in excellent condition with premium features.',
          highlights: ['Low mileage', 'Luxury features', 'Excellent condition'],
          issues: [],
          recommendations: ['Regular Lexus service', 'Premium fuel'],
        },
        trustScore: 94.0,
        verdict: 'Excellent',
        status: 'completed',
      },
      {
        userId: savedUsers[14].id,
        make: 'Acura',
        model: 'RDX',
        year: 2020,
        carDetails: {
          kilometersDriven: 40000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Apex Blue',
          ownershipCount: 1,
          vin: '5J8TD3H35LL123456',
          registrationNumber: 'TN-WXY901',
          city: 'Nashville',
          state: 'Tennessee',
          country: 'USA',
          engine: '2.0L Turbo 4-Cylinder',
          drivetrain: 'AWD',
          condition: 'Very Good',
          features: ['AcuraWatch', 'ELS Studio Audio', 'Panoramic Roof', 'Leather Seats'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 89,
          status: 'completed',
          summary: 'Premium SUV with advanced safety features and good condition.',
          highlights: ['Safety features', 'Premium audio', 'Good condition'],
          issues: [],
          recommendations: ['Regular Acura service'],
        },
        trustScore: 89.0,
        verdict: 'Very Good',
        status: 'completed',
      },
      {
        userId: savedUsers[0].id,
        make: 'Toyota',
        model: 'RAV4',
        year: 2021,
        carDetails: {
          kilometersDriven: 35000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Lunar Rock',
          ownershipCount: 1,
          vin: 'JTMB1RFV8MD123456',
          registrationNumber: 'CA-ZAB234',
          city: 'Los Angeles',
          state: 'California',
          country: 'USA',
          engine: '2.5L 4-Cylinder',
          drivetrain: 'AWD',
          condition: 'Excellent',
          features: ['Toyota Safety Sense', 'Apple CarPlay', 'Android Auto', 'AWD'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 91,
          status: 'completed',
          summary: 'Excellent compact SUV with modern features and good reliability.',
          highlights: ['Low mileage', 'Modern features', 'Reliable'],
          issues: [],
          recommendations: ['Regular maintenance'],
        },
        trustScore: 91.0,
        verdict: 'Excellent',
        status: 'completed',
      },
      {
        userId: savedUsers[1].id,
        make: 'Honda',
        model: 'Accord',
        year: 2020,
        carDetails: {
          kilometersDriven: 47000,
          fuelType: 'Gasoline',
          transmission: 'CVT',
          color: 'Platinum White',
          ownershipCount: 1,
          vin: '1HGCV1F30LA123456',
          registrationNumber: 'NY-CDE567',
          city: 'New York',
          state: 'New York',
          country: 'USA',
          engine: '1.5L Turbo 4-Cylinder',
          drivetrain: 'FWD',
          condition: 'Very Good',
          features: ['Honda Sensing', 'Apple CarPlay', 'Android Auto', 'Leather Seats'],
        },
        media: { images: getCarImages(0), videos: [] },
        aiAnalysis: {
          overallScore: 87,
          status: 'completed',
          summary: 'Well-maintained midsize sedan with modern safety features.',
          highlights: ['Safety features', 'Modern tech', 'Good condition'],
          issues: [],
          recommendations: ['Regular maintenance'],
        },
        trustScore: 87.0,
        verdict: 'Very Good',
        status: 'completed',
      },
      {
        userId: savedUsers[2].id,
        make: 'Tesla',
        model: 'Model Y',
        year: 2022,
        carDetails: {
          kilometersDriven: 12000,
          fuelType: 'Electric',
          transmission: 'Single-Speed',
          color: 'Midnight Silver',
          ownershipCount: 1,
          vin: '5YJYGDEE6NF123456',
          registrationNumber: 'FL-FGH890',
          city: 'Miami',
          state: 'Florida',
          country: 'USA',
          engine: 'Dual Motor',
          drivetrain: 'AWD',
          condition: 'Like New',
          features: ['Autopilot', 'Supercharging', 'Premium Interior', '7-Seat Option'],
        },
        media: { images: getCarImages(3), videos: [] },
        aiAnalysis: {
          overallScore: 97,
          status: 'completed',
          summary: 'Nearly new electric SUV with cutting-edge technology.',
          highlights: ['Very low mileage', 'Latest tech', 'Excellent condition'],
          issues: [],
          recommendations: ['Battery health check'],
        },
        trustScore: 97.0,
        verdict: 'Like New',
        status: 'completed',
      },
      {
        userId: savedUsers[3].id,
        make: 'Ford',
        model: 'Mustang',
        year: 2020,
        carDetails: {
          kilometersDriven: 30000,
          fuelType: 'Gasoline',
          transmission: 'Manual',
          color: 'Race Red',
          ownershipCount: 1,
          vin: '1FA6P8TH5L5123456',
          registrationNumber: 'IL-IJK123',
          city: 'Chicago',
          state: 'Illinois',
          country: 'USA',
          engine: '5.0L V8',
          drivetrain: 'RWD',
          condition: 'Excellent',
          features: ['Performance Package', 'Recaro Seats', 'MagneRide Suspension', 'Active Exhaust'],
        },
        media: { images: getCarImages(0), videos: [] },
        aiAnalysis: {
          overallScore: 90,
          status: 'completed',
          summary: 'Excellent performance car with low mileage and premium features.',
          highlights: ['Low mileage', 'Performance features', 'Well-maintained'],
          issues: [],
          recommendations: ['Premium fuel only', 'Regular maintenance'],
        },
        trustScore: 90.0,
        verdict: 'Excellent',
        status: 'completed',
      },
      {
        userId: savedUsers[4].id,
        make: 'Chevrolet',
        model: 'Equinox',
        year: 2021,
        carDetails: {
          kilometersDriven: 28000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Summit White',
          ownershipCount: 1,
          vin: '2GNALBEKXM123456',
          registrationNumber: 'TX-LMN456',
          city: 'Houston',
          state: 'Texas',
          country: 'USA',
          engine: '1.5L Turbo 4-Cylinder',
          drivetrain: 'FWD',
          condition: 'Very Good',
          features: ['Chevrolet Infotainment', 'Apple CarPlay', 'Android Auto', 'Safety Features'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 88,
          status: 'completed',
          summary: 'Well-maintained compact SUV with modern features.',
          highlights: ['Low mileage', 'Modern features', 'Good condition'],
          issues: [],
          recommendations: ['Regular maintenance'],
        },
        trustScore: 88.0,
        verdict: 'Very Good',
        status: 'completed',
      },
      {
        userId: savedUsers[5].id,
        make: 'Nissan',
        model: 'Rogue',
        year: 2021,
        carDetails: {
          kilometersDriven: 33000,
          fuelType: 'Gasoline',
          transmission: 'CVT',
          color: 'Pearl White',
          ownershipCount: 1,
          vin: 'JN1AZ4EH1MW123456',
          registrationNumber: 'AZ-NOP789',
          city: 'Phoenix',
          state: 'Arizona',
          country: 'USA',
          engine: '2.5L 4-Cylinder',
          drivetrain: 'AWD',
          condition: 'Very Good',
          features: ['Nissan Safety Shield', 'Apple CarPlay', 'Android Auto', 'ProPILOT Assist'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 86,
          status: 'completed',
          summary: 'Modern SUV with advanced safety features and good condition.',
          highlights: ['Safety features', 'Modern tech', 'Good condition'],
          issues: [],
          recommendations: ['Check CVT fluid', 'Regular maintenance'],
        },
        trustScore: 86.0,
        verdict: 'Very Good',
        status: 'completed',
      },
      {
        userId: savedUsers[6].id,
        make: 'Subaru',
        model: 'Forester',
        year: 2020,
        carDetails: {
          kilometersDriven: 50000,
          fuelType: 'Gasoline',
          transmission: 'CVT',
          color: 'Crystal White Pearl',
          ownershipCount: 1,
          vin: 'JF2SKAEC0LH123456',
          registrationNumber: 'WA-QRS012',
          city: 'Seattle',
          state: 'Washington',
          country: 'USA',
          engine: '2.5L Boxer 4-Cylinder',
          drivetrain: 'AWD',
          condition: 'Good',
          features: ['Subaru EyeSight', 'AWD', 'X-Mode', 'Roof Rails'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 85,
          status: 'completed',
          summary: 'Reliable AWD SUV with good safety features.',
          highlights: ['AWD system', 'Safety features', 'Reliable'],
          issues: ['Some wear expected for mileage'],
          recommendations: ['Check CVT fluid', 'Replace tires if needed'],
        },
        trustScore: 85.0,
        verdict: 'Good',
        status: 'completed',
      },
      {
        userId: savedUsers[7].id,
        make: 'Mazda',
        model: 'Mazda3',
        year: 2021,
        carDetails: {
          kilometersDriven: 26000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Polymetal Gray',
          ownershipCount: 1,
          vin: 'JM1BN1U75M1123456',
          registrationNumber: 'MA-STU345',
          city: 'Boston',
          state: 'Massachusetts',
          country: 'USA',
          engine: '2.5L Skyactiv-G',
          drivetrain: 'FWD',
          condition: 'Excellent',
          features: ['Mazda Connect', 'i-Activsense', 'Bose Audio', 'Leather Seats'],
        },
        media: { images: getCarImages(0), videos: [] },
        aiAnalysis: {
          overallScore: 90,
          status: 'completed',
          summary: 'Excellent compact car with premium features and low mileage.',
          highlights: ['Low mileage', 'Premium features', 'Great handling'],
          issues: [],
          recommendations: ['Continue regular maintenance'],
        },
        trustScore: 90.0,
        verdict: 'Excellent',
        status: 'completed',
      },
      {
        userId: savedUsers[8].id,
        make: 'GMC',
        model: 'Sierra',
        year: 2020,
        carDetails: {
          kilometersDriven: 52000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Summit White',
          ownershipCount: 1,
          vin: '1GT49REY0LF123456',
          registrationNumber: 'CO-VWX678',
          city: 'Denver',
          state: 'Colorado',
          country: 'USA',
          engine: '5.3L V8',
          drivetrain: '4WD',
          condition: 'Good',
          features: ['4WD', 'GMC Infotainment', 'Towing Package', 'Backup Camera'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 83,
          status: 'completed',
          summary: 'Powerful truck with good features, some wear expected.',
          highlights: ['Powerful engine', 'Good features'],
          issues: ['Some wear', 'Tires may need replacement'],
          recommendations: ['Replace tires', 'Check brake pads'],
        },
        trustScore: 83.0,
        verdict: 'Good',
        status: 'completed',
      },
      {
        userId: savedUsers[9].id,
        make: 'Toyota',
        model: 'Highlander',
        year: 2021,
        carDetails: {
          kilometersDriven: 24000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Midnight Black',
          ownershipCount: 1,
          vin: '5TDKZ3DC1MS123456',
          registrationNumber: 'GA-YZA901',
          city: 'Atlanta',
          state: 'Georgia',
          country: 'USA',
          engine: '3.5L V6',
          drivetrain: 'AWD',
          condition: 'Excellent',
          features: ['Toyota Safety Sense', 'Apple CarPlay', 'Android Auto', 'Third Row Seating'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 92,
          status: 'completed',
          summary: 'Excellent family SUV with low mileage and premium features.',
          highlights: ['Low mileage', 'Spacious', 'Reliable'],
          issues: [],
          recommendations: ['Regular maintenance'],
        },
        trustScore: 92.0,
        verdict: 'Excellent',
        status: 'completed',
      },
      {
        userId: savedUsers[10].id,
        make: 'BMW',
        model: 'X5',
        year: 2021,
        carDetails: {
          kilometersDriven: 20000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Mineral White',
          ownershipCount: 1,
          vin: '5UXCR6C05M9123456',
          registrationNumber: 'CA-ABC234',
          city: 'San Francisco',
          state: 'California',
          country: 'USA',
          engine: '3.0L Turbo I6',
          drivetrain: 'AWD',
          condition: 'Excellent',
          features: ['iDrive 7', 'Panoramic Roof', 'Premium Sound', 'Leather Seats'],
        },
        media: { images: getCarImages(2), videos: [] },
        aiAnalysis: {
          overallScore: 95,
          status: 'completed',
          summary: 'Luxury SUV in excellent condition with very low mileage.',
          highlights: ['Very low mileage', 'Luxury features', 'Excellent condition'],
          issues: [],
          recommendations: ['Premium fuel', 'Regular BMW service'],
        },
        trustScore: 95.0,
        verdict: 'Excellent',
        status: 'completed',
      },
      {
        userId: savedUsers[11].id,
        make: 'Honda',
        model: 'Pilot',
        year: 2020,
        carDetails: {
          kilometersDriven: 44000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Obsidian Blue',
          ownershipCount: 1,
          vin: '5FNYF4H90LB123456',
          registrationNumber: 'OR-BCD567',
          city: 'Portland',
          state: 'Oregon',
          country: 'USA',
          engine: '3.5L V6',
          drivetrain: 'AWD',
          condition: 'Very Good',
          features: ['Honda Sensing', 'Apple CarPlay', 'Android Auto', 'Third Row Seating'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 88,
          status: 'completed',
          summary: 'Well-maintained large SUV with good features.',
          highlights: ['Spacious', 'Safety features', 'Good condition'],
          issues: [],
          recommendations: ['Regular maintenance'],
        },
        trustScore: 88.0,
        verdict: 'Very Good',
        status: 'completed',
      },
      {
        userId: savedUsers[12].id,
        make: 'Ford',
        model: 'Explorer',
        year: 2021,
        carDetails: {
          kilometersDriven: 31000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Agate Black',
          ownershipCount: 1,
          vin: '1FM5K8D81MGA12345',
          registrationNumber: 'TX-DEF890',
          city: 'Dallas',
          state: 'Texas',
          country: 'USA',
          engine: '2.3L EcoBoost',
          drivetrain: 'AWD',
          condition: 'Very Good',
          features: ['SYNC 4', 'Apple CarPlay', 'Android Auto', 'Third Row Seating'],
        },
        media: { images: getCarImages(1), videos: [] },
        aiAnalysis: {
          overallScore: 87,
          status: 'completed',
          summary: 'Modern SUV with good features and low mileage.',
          highlights: ['Low mileage', 'Modern tech', 'Spacious'],
          issues: [],
          recommendations: ['Regular maintenance'],
        },
        trustScore: 87.0,
        verdict: 'Very Good',
        status: 'completed',
      },
      {
        userId: savedUsers[13].id,
        make: 'Mercedes-Benz',
        model: 'GLC',
        year: 2021,
        carDetails: {
          kilometersDriven: 19000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Obsidian Black',
          ownershipCount: 1,
          vin: 'WDC0G4KB1MR123456',
          registrationNumber: 'NV-EFG123',
          city: 'Las Vegas',
          state: 'Nevada',
          country: 'USA',
          engine: '2.0L Turbo 4-Cylinder',
          drivetrain: 'AWD',
          condition: 'Excellent',
          features: ['MBUX', 'Panoramic Roof', 'Burmester Sound', 'AMG Line'],
        },
        media: { images: getCarImages(2), videos: [] },
        aiAnalysis: {
          overallScore: 94,
          status: 'completed',
          summary: 'Luxury SUV in excellent condition with very low mileage.',
          highlights: ['Very low mileage', 'Luxury features', 'Excellent condition'],
          issues: [],
          recommendations: ['Premium fuel', 'Regular Mercedes service'],
        },
        trustScore: 94.0,
        verdict: 'Excellent',
        status: 'completed',
      },
      {
        userId: savedUsers[14].id,
        make: 'Audi',
        model: 'Q5',
        year: 2021,
        carDetails: {
          kilometersDriven: 27000,
          fuelType: 'Gasoline',
          transmission: 'Automatic',
          color: 'Navarra Blue',
          ownershipCount: 1,
          vin: 'WA1BNAFY1M2123456',
          registrationNumber: 'TN-FGH456',
          city: 'Nashville',
          state: 'Tennessee',
          country: 'USA',
          engine: '2.0L Turbo 4-Cylinder',
          drivetrain: 'AWD',
          condition: 'Excellent',
          features: ['Virtual Cockpit', 'Bang & Olufsen', 'Panoramic Roof', 'Quattro AWD'],
        },
        media: { images: getCarImages(2), videos: [] },
        aiAnalysis: {
          overallScore: 91,
          status: 'completed',
          summary: 'Premium SUV with advanced features and excellent condition.',
          highlights: ['Low mileage', 'Premium features', 'Excellent condition'],
          issues: [],
          recommendations: ['Premium fuel', 'Regular Audi service'],
        },
        trustScore: 91.0,
        verdict: 'Excellent',
        status: 'completed',
      },
    ];

    const savedReports = await reportRepository.save(reports);
    console.log(`✅ Created ${savedReports.length} reports`);

    // Create marketplace listings
    console.log('🏪 Creating marketplace listings...');
    const listings = [
      {
        userId: savedUsers[0].id,
        reportId: savedReports[0].id,
        price: 24500,
        currency: 'USD',
        city: 'Los Angeles',
        state: 'California',
        isActive: true,
      },
      {
        userId: savedUsers[1].id,
        reportId: savedReports[1].id,
        price: 22500,
        currency: 'USD',
        city: 'New York',
        state: 'New York',
        isActive: true,
      },
      {
        userId: savedUsers[0].id,
        reportId: savedReports[2].id,
        price: 42000,
        currency: 'USD',
        city: 'Los Angeles',
        state: 'California',
        isActive: true,
      },
      {
        userId: savedUsers[2].id,
        reportId: savedReports[3].id,
        price: 38000,
        currency: 'USD',
        city: 'Miami',
        state: 'Florida',
        isActive: true,
      },
      {
        userId: savedUsers[1].id,
        reportId: savedReports[4].id,
        price: 35000,
        currency: 'USD',
        city: 'New York',
        state: 'New York',
        isActive: true,
      },
      {
        userId: savedUsers[2].id,
        reportId: savedReports[5].id,
        price: 41000,
        currency: 'USD',
        city: 'Miami',
        state: 'Florida',
        isActive: true,
      },
      {
        userId: savedUsers[3].id,
        reportId: savedReports[6].id,
        price: 36000,
        currency: 'USD',
        city: 'Chicago',
        state: 'Illinois',
        isActive: true,
      },
      {
        userId: savedUsers[4].id,
        reportId: savedReports[7].id,
        price: 19500,
        currency: 'USD',
        city: 'Houston',
        state: 'Texas',
        isActive: true,
      },
      {
        userId: savedUsers[5].id,
        reportId: savedReports[8].id,
        price: 28500,
        currency: 'USD',
        city: 'Phoenix',
        state: 'Arizona',
        isActive: true,
      },
      {
        userId: savedUsers[6].id,
        reportId: savedReports[9].id,
        price: 32000,
        currency: 'USD',
        city: 'Seattle',
        state: 'Washington',
        isActive: true,
      },
      {
        userId: savedUsers[7].id,
        reportId: savedReports[10].id,
        price: 31000,
        currency: 'USD',
        city: 'Boston',
        state: 'Massachusetts',
        isActive: true,
      },
      {
        userId: savedUsers[8].id,
        reportId: savedReports[11].id,
        price: 45000,
        currency: 'USD',
        city: 'Denver',
        state: 'Colorado',
        isActive: true,
      },
      {
        userId: savedUsers[9].id,
        reportId: savedReports[12].id,
        price: 42000,
        currency: 'USD',
        city: 'Atlanta',
        state: 'Georgia',
        isActive: true,
      },
      {
        userId: savedUsers[10].id,
        reportId: savedReports[13].id,
        price: 18500,
        currency: 'USD',
        city: 'San Francisco',
        state: 'California',
        isActive: true,
      },
      {
        userId: savedUsers[11].id,
        reportId: savedReports[14].id,
        price: 48000,
        currency: 'USD',
        city: 'Portland',
        state: 'Oregon',
        isActive: true,
      },
      {
        userId: savedUsers[12].id,
        reportId: savedReports[15].id,
        price: 44000,
        currency: 'USD',
        city: 'Dallas',
        state: 'Texas',
        isActive: true,
      },
      {
        userId: savedUsers[13].id,
        reportId: savedReports[16].id,
        price: 52000,
        currency: 'USD',
        city: 'Las Vegas',
        state: 'Nevada',
        isActive: true,
      },
      {
        userId: savedUsers[14].id,
        reportId: savedReports[17].id,
        price: 38000,
        currency: 'USD',
        city: 'Nashville',
        state: 'Tennessee',
        isActive: true,
      },
      {
        userId: savedUsers[0].id,
        reportId: savedReports[18].id,
        price: 33000,
        currency: 'USD',
        city: 'Los Angeles',
        state: 'California',
        isActive: true,
      },
      {
        userId: savedUsers[1].id,
        reportId: savedReports[19].id,
        price: 26000,
        currency: 'USD',
        city: 'New York',
        state: 'New York',
        isActive: true,
      },
      {
        userId: savedUsers[2].id,
        reportId: savedReports[20].id,
        price: 45000,
        currency: 'USD',
        city: 'Miami',
        state: 'Florida',
        isActive: true,
      },
      {
        userId: savedUsers[3].id,
        reportId: savedReports[21].id,
        price: 39000,
        currency: 'USD',
        city: 'Chicago',
        state: 'Illinois',
        isActive: true,
      },
      {
        userId: savedUsers[4].id,
        reportId: savedReports[22].id,
        price: 27000,
        currency: 'USD',
        city: 'Houston',
        state: 'Texas',
        isActive: true,
      },
      {
        userId: savedUsers[5].id,
        reportId: savedReports[23].id,
        price: 29000,
        currency: 'USD',
        city: 'Phoenix',
        state: 'Arizona',
        isActive: true,
      },
      {
        userId: savedUsers[6].id,
        reportId: savedReports[24].id,
        price: 28000,
        currency: 'USD',
        city: 'Seattle',
        state: 'Washington',
        isActive: true,
      },
      {
        userId: savedUsers[7].id,
        reportId: savedReports[25].id,
        price: 26500,
        currency: 'USD',
        city: 'Boston',
        state: 'Massachusetts',
        isActive: true,
      },
      {
        userId: savedUsers[8].id,
        reportId: savedReports[26].id,
        price: 43000,
        currency: 'USD',
        city: 'Denver',
        state: 'Colorado',
        isActive: true,
      },
      {
        userId: savedUsers[9].id,
        reportId: savedReports[27].id,
        price: 40000,
        currency: 'USD',
        city: 'Atlanta',
        state: 'Georgia',
        isActive: true,
      },
      {
        userId: savedUsers[10].id,
        reportId: savedReports[28].id,
        price: 65000,
        currency: 'USD',
        city: 'San Francisco',
        state: 'California',
        isActive: true,
      },
      {
        userId: savedUsers[11].id,
        reportId: savedReports[29].id,
        price: 34000,
        currency: 'USD',
        city: 'Portland',
        state: 'Oregon',
        isActive: true,
      },
    ];

    const savedListings = await listingRepository.save(listings);
    console.log(`✅ Created ${savedListings.length} marketplace listings`);

    console.log('\n🎉 Seed completed successfully!');
    console.log('\n📋 Summary:');
    console.log(`   - Users: ${savedUsers.length}`);
    console.log(`   - Reports: ${savedReports.length}`);
    console.log(`   - Listings: ${savedListings.length}`);
    console.log('\n🔗 Test the API at: http://localhost:3001/api/marketplace');
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    throw error;
  } finally {
    await dataSource.destroy();
  }
}

seed();
