"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

export default function SuccessPage() {
  const router = useRouter();

  return (
    <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-blue-50 via-white to-indigo-50 px-4 py-12 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
      <div className="w-full max-w-md text-center">
        <div className="mb-6 text-7xl">✅</div>
        <h1 className="mb-4 text-3xl font-bold text-gray-900 dark:text-white sm:text-4xl">
          Report Submitted Successfully!
        </h1>
        <p className="mb-8 text-lg text-gray-600 dark:text-gray-400">
          Your car health report is being generated by our AI. You'll receive
          it via email/SMS once it's ready.
        </p>

        <div className="space-y-4">
          <Link
            href="/"
            className="block rounded-xl bg-blue-600 px-8 py-4 text-base font-semibold text-white transition-colors hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-600"
          >
            Back to Home
          </Link>
          <button
            onClick={() => router.back()}
            className="block w-full rounded-xl border-2 border-gray-300 px-8 py-4 text-base font-semibold text-gray-700 transition-colors hover:bg-gray-50 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-700"
          >
            View Report
          </button>
        </div>

        <div className="mt-8 rounded-lg bg-blue-50 p-4 dark:bg-blue-900/20">
          <p className="text-sm text-gray-700 dark:text-gray-300">
            <span className="font-semibold">⏱️ Processing Time:</span> Your
            report will be ready in approximately 5-10 minutes. We'll notify
            you when it's complete.
          </p>
        </div>
      </div>
    </div>
  );
}
